#BSUB -n 1
#BSUB -o out

make pnp_steadystate_box

# ------> 用解析解计算收敛阶
./pnp_box/pnp_steadystate_box -p 1 -ref 3 -lin gummel -dis cg -rate
./pnp_box/pnp_steadystate_box -p 1 -ref 3 -lin gummel -dis dg -rate
./pnp_box/pnp_steadystate_box -p 1 -ref 3 -lin newton -dis cg -rate
./pnp_box/pnp_steadystate_box -p 1 -ref 3 -lin newton -dis dg -rate


make pnp_steadystate_protein

# ------>
./pnp_protein/pnp_steadystate_protein -p 1 -lin gummel -dis cg
./pnp_protein/pnp_steadystate_protein -p 1 -lin newton -dis cg

